version: '3.9'
services:
    kavita:
        image: kizaing/kavita:latest
        volumes:
            - ./manga:/manga
            - ./data:/kavita/config
            - media:/mnt/media

        ports:
            - "5000:5000"
        restart: unless-stopped

volumes:
  media:
    driver_opts:
      type: "nfs"
      o: "addr=IP,nolock,ro,soft,nfsvers=4"
      device: ":/mnt/to/storage"

networks:
  default:
    name: m-va
    external: true
